# Generated by Django 5.2.5 on 2025-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="mode",
            field=models.CharField(
                choices=[("api", "API"), ("internal", "Internal")], max_length=20
            ),
        ),
    ]
