# Generated by Django 5.2.5 on 2025-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
