# Generated by Django 5.2.5 on 2025-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_comment_likes_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
