# Generated by Django 5.2.5 on 2025-09-09 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_comment_likes_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.chatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "chat_image",
                "ordering": ["created_at"],
            },
        ),
    ]
