# Generated by Django 5.2.5 on 2025-09-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_chatimage"),
        ("main", "0006_comment_likes_post_likes"),
    ]

    operations = []
