# Generated by Django 5.2.5 on 2025-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_merge_0006_chatimage_0006_comment_likes_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("tool_calls", "Tool Calls"),
                    ("tool_responses", "Tool Responses"),
                ],
                max_length=20,
            ),
        ),
    ]
