# Generated by Django 5.2.5 on 2025-09-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frontend", "프론트엔드팀"),
                    ("backend", "백엔드팀"),
                    ("data_ai", "데이터/AI팀"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("female", "여성"), ("male", "남성")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rank",
            field=models.CharField(
                choices=[("general", "일반"), ("cto", "CTO")], max_length=50
            ),
        ),
    ]
