# Generated by Django 5.2.4 on 2025-09-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0002_alter_user_department_alter_user_gender_and_more"),
        ("uauth", "0002_alter_user_is_active"),
    ]

    operations = []
