# Generated by Django 5.2.5 on 2025-09-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0003_merge_20250905_1228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
