# Generated by Django 5.2.4 on 2025-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
