# Generated by Django 5.2.4 on 2025-09-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0005_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
