# Generated by Django 5.2.4 on 2025-09-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(
                default="https://skn14-codenova-profile.s3.ap-northeast-2.amazonaws.com/profile_image/default2.png",
                max_length=500,
            ),
        ),
    ]
